# Generated by Django 3.2.5 on 2021-07-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blog_WEB!!!', max_length=255),
        ),
    ]
