# Generated by Django 3.2.5 on 2021-07-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Blog', '0003_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
